version: '3.8'

services:
  php:
    container_name: scoutbasketball-symfony-php
    build:
      context: ./docker/php
    ports:
      - '9001:9001'
    volumes:
      - ./app:/var/www/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    depends_on:
      - database

  database:
    container_name: scoutbasketball-symfony-database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: scoutbasketball
      MYSQL_USER: db-user
      MYSQL_PASSWORD: db-pass
    ports:
      - '11002:3306'
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  nginx:
    container_name: scoutbasketball-symfony-nginx
    image: nginx:stable-alpine
    ports:
      - '11001:80'
    volumes:
      - ./app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
