name: CI

on: [push]

defaults:
  run:
    working-directory: app

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - uses: actions/checkout@v3

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist

      - name: Run Easy Coding Standard
        run: php vendor/bin/ecs check

      - name: Run PhpUnit
        run: vendor/bin/phpunit

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --xdebug

      - name: Run Rector
        run: vendor/bin/rector process --dry-run

      - name: Save coverage
        run: |
          echo "COVERAGE=$(grep -oP '(?<=Lines:   )(\d{0,2}\.\d{0,2})' var/coverage/coverage.txt)" >> $GITHUB_ENV

      - name: Create coverage Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 0c1f8403decd5753c549451042d2c952
          filename: scoutbasketball-symfony-coverage.json
          label: Coverage
          message: ${{ env.COVERAGE }}%
          valColorRange: ${{ env.COVERAGE }}
          maxColorRange: 100
          minColorRange: 0